### ISSUE TITLE
Congratulations!!!

### ISSUE THREAD

**Issue by yakode** [sg20180546/ZNS-awesome-paper#1]
I study in ZNS SSD, and have followed this awesome repo for a while. This repo is really helpful for me! Thank you <3
Today, I am reading a paper named "A Free-Space Adaptive Runtime Zone-Reset Algorithm for Enhanced ZNS Efficiency". I suddenly find out it is your paper!
OMG! You also write an awesome paper:) Congratulations!

**Comment by sg20180546** [comment]
thank you so much ! if you get new other zns paper, feel free to commit here.

**Comment by technosoft-admin** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @hyun99999, @daniil-shumko, @batz-gg, @KarlZeo, @vdrabll, @mome13, @nepnym, @binglumeng, @roketdigital, @martinronquillo, @Tomiyin001, @artking28, @zool-keda1, @roblesmontanari, @aftahiArdi, @akdag70, @zhxzing, @lucas-glopes, @rsburr, @Ficky97

**Comment by Tomiyin001** [comment]
How can i claim my reward please

**Comment by lucas-glopes** [comment]
Hello,

Could anyone please explain me what is it ? I was mentioned and I don’t
even know what this whole thing is.

Em seg., 29 de jan. de 2024 às 06:09, Tomiyin001 ***@***.***>
escreveu:
